language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "pypy"
before_install:
    - sudo sh -c "echo 'deb http://archive.ubuntu.com/ubuntu/ precise multiverse' >> /etc/apt/sources.list"
    - sudo sh -c "echo 'deb http://archive.ubuntu.com/ubuntu/ precise-updates multiverse' >> /etc/apt/sources.list"
    - sudo apt-get update -qq
    - sudo apt-get install -qq nvidia-cg-toolkit libgl1-mesa-dev
    - pip install cython
install: "pip install ."
script: nosetests
